print("============[INFO]============")
print("Name           : Zhunge liang")
print("ID             : 42069")
print("Birth of date  : 01/01/2000")
print("Nationality    : China")
print("Skill          : Software Dev")
print("============[####]============")
